import { BadRequestException, ForbiddenException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Role } from '../common/enums/role.enum';
import type { AuthenticatedUser } from '../common/interfaces/authenticated-user.interface';
import { CasosService } from '../simulacion/casos.service';
import { AiAssetsService } from './ai-assets.service';
import { PromptBuilderService } from './prompt-builder.service';

describe('AiAssetsService', () => {
  const currentUser: AuthenticatedUser = {
    sub: 'docente-1',
    email: 'docente@example.com',
    role: Role.PROFESOR,
    tokenVersion: 1,
  };

  let service: AiAssetsService;
  let postgrest: {
    select: jest.Mock;
    insert: jest.Mock;
    update: jest.Mock;
  };
  let casosService: {
    findCasoById: jest.Mock;
    assertCanAccessCasoDocente: jest.Mock;
  };

  beforeEach(() => {
    postgrest = {
      select: jest.fn(),
      insert: jest.fn(),
      update: jest.fn(),
    };
    casosService = {
      findCasoById: jest.fn(),
      assertCanAccessCasoDocente: jest.fn(),
    };
    service = new AiAssetsService(
      postgrest as never,
      casosService as never,
      new PromptBuilderService(),
      {
        get: jest.fn((key: string, defaultValue?: string) => {
          if (key === 'APP_PUBLIC_URL') {
            return 'http://localhost:3000';
          }
          return defaultValue;
        }),
      } as unknown as ConfigService,
    );
  });

  it('rejects applying a non-background asset in the MVP', async () => {
    casosService.findCasoById.mockResolvedValue({ id: 'caso-1', autor_docente_id: 'docente-1' });
    postgrest.select
      .mockResolvedValueOnce([
        {
          id: 'asset-1',
          caso_id: 'caso-1',
          escenario_id: null,
          docente_id: 'docente-1',
          tipo: 'OBJETO',
          nombre: 'objeto',
          prompt_original: 'obj',
          prompt_final: 'obj',
          url_externa: 'https://image.pollinations.ai/prompt/test',
          ruta_archivo: '/uploads/ai-assets/test.jpg',
          ancho: 1280,
          alto: 720,
          estilo: 'editorial_sereno',
          proveedor: 'pollinations',
          created_at: new Date().toISOString(),
        },
      ]);

    await expect(
      service.insertIntoScenario('asset-1', { escenarioId: 'esc-1' }, currentUser),
    ).rejects.toBeInstanceOf(BadRequestException);
  });

  it('rejects applying an asset generated by another docente', async () => {
    casosService.findCasoById.mockResolvedValue({ id: 'caso-1', autor_docente_id: 'docente-2' });
    postgrest.select
      .mockResolvedValueOnce([
        {
          id: 'asset-1',
          caso_id: 'caso-1',
          escenario_id: null,
          docente_id: 'docente-2',
          tipo: 'FONDO',
          nombre: 'fondo',
          prompt_original: 'fondo',
          prompt_final: 'fondo',
          url_externa: 'https://image.pollinations.ai/prompt/test',
          ruta_archivo: '/uploads/ai-assets/test.jpg',
          ancho: 1280,
          alto: 720,
          estilo: 'editorial_sereno',
          proveedor: 'pollinations',
          created_at: new Date().toISOString(),
        },
      ]);

    await expect(
      service.insertIntoScenario('asset-1', { escenarioId: 'esc-1' }, currentUser),
    ).rejects.toBeInstanceOf(ForbiddenException);
  });
});
